#!/bin/bash

# a helper script to track updates on how to run dev server with file watchers,
# and host configuration that ensure gatsby develop works properly.

export CHOKIDAR_USEPOLLING=1
hostName="0.0.0.0" # localhost is also valid but doesn't host on net
if [[ $# == 1 ]]; then
    hostName=$1
fi
gatsby develop --host $hostName
